services:
  soft-redirections-cms-postgres:
    container_name: soft-redirections-cms-postgres
    image: postgres:14.3-alpine
    platform: linux/amd64
    env_file: ./cms/.env
    ports:
      - '5432:5432'
    volumes:
      - soft-redirections-cms-sql-data:/var/lib/postgresql/data/
    networks:
      - soft-redirections-network

  soft-redirections-cms:
    container_name: soft-redirections-cms
    build: ./cms
    image: strapi:latest
    env_file: ./cms/.env
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ./cms:/usr/src/app
    ports:
      - "1337:1337"
    networks:
      - soft-redirections-network
    depends_on:
      - soft-redirections-cms-postgres
      - soft-redirections-backend-postgres
    command: npm run develop

  soft-redirections-backend:
    container_name: soft-redirections-backend
    build: ./backend
    env_file: ./backend/.env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    networks:
      - soft-redirections-network
    command: npm run dev

  soft-redirections-backend-postgres:
    container_name: soft-redirections-backend-postgres
    image: postgres:14.3-alpine
    platform: linux/amd64
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=backend
    ports:
      - '5433:5433'
    volumes:
      - soft-redirections-backend-sql-data:/var/lib/postgresql/data/
    networks:
      - soft-redirections-network

  soft-redirections-frontend:
    container_name: soft-redirections-frontend
    build: ./frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - soft-redirections-network
    command: npm run dev

volumes:
  soft-redirections-cms-sql-data:
  soft-redirections-backend-sql-data:

networks:
  soft-redirections-network:
    driver: bridge
