services:
#  soft-redirections_backend:
#    build: ./backend
##    user: 65648:513
#    command: >
#      sh -c "npm install -g nodemon && ${DOCKER_COMMAND:-npm run start}"
#    container_name: soft-redirections_backend
#    environment:
#      - SR_ENV=development
#    ports:
#      - "4000:4000"
#    volumes:
#      - ./backend:/usr/src/app
#    networks:
#      - soft-redirections-dev

#  soft-redirections_frontend:
#    build: ./frontend
#    command: >
#      sh -c "${DOCKER_COMMAND:-npm run dev}"
#    container_name: soft-redirections_frontend
#    environment:
#      - SR_ENV=development
#    ports:
#      - "3004:3004"
#    volumes:
#      - ./frontend:/usr/src/app
#    networks:
#      - soft-redirections-dev

  soft-redirections-cms-postgres:
    container_name: soft-redirections-cms-postgres
    image: postgres:14.3-alpine
    platform: linux/amd64
    env_file: ./cms/.env
    ports:
      - '5432:5432'
    volumes:
      - soft-redirections-sql-data:/var/lib/postgresql/data/
    networks:
      - soft-redirections-network

  soft-redirections-cms:
    container_name: soft-redirections-cms
    build: ./cms
    image: strapi:latest
    env_file: ./cms/.env
    volumes:
      - ./cms/:/opt/app
    ports:
      - "1337:1337"
    networks:
      - soft-redirections-network
    depends_on:
      - soft-redirections-cms-postgres

volumes:
  soft-redirections-sql-data:

networks:
  soft-redirections-network:
    driver: bridge
